### ISSUE TITLE
MongoDB 3.6.2 sh.status missing function 

### ISSUE THREAD

**Issue by desterhuizen** [TylerBrock/mongo-hacker#184] opened 2018-02-07 17:53 UTC
MongoDB 3.6.2 removes the function sh.getBalancerLockDetails.

Connecting to a sharded cluster when mongo-hacker is installed then causes the following exception when running sh.status()

```
[mongos] test> sh.status()
2018-02-07T12:48:57.040-0500 E QUERY    [thread1] TypeError: sh.getBalancerLockDetails is not a function :
sh.status@src/mongo/shell/utils_sh.js:89:5
@(shell):1:1
```

**Comment by TylerBrock** [comment] 2018-02-17 17:51
Thanks for reporting this!

**Comment by kagahd** [comment] 2018-09-20 12:26
See workaround here: https://github.com/TylerBrock/mongo-hacker/issues/197

**Comment by stennie** [comment] 2019-08-24 03:34
Closing as a duplicate of #197

**Closed by stennie** 2019-08-24 03:34 UTC
